# Generated by Django 5.1.4 on 2024-12-22 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_user_field(apps, schema_editor):
    """Populate the user field with a default user for existing subscriptions."""
    Subscription = apps.get_model('subscriptions', 'Subscription')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Get a default user (create one if necessary)
    default_user, _ = User.objects.get_or_create(username='default_user', defaults={'email': 'default@example.com'})
    
    # Update subscriptions with null user
    for subscription in Subscription.objects.filter(user__isnull=True):
        subscription.user = default_user
        subscription.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Temporarily allow null for the 'user' field
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscription',
                to=settings.AUTH_USER_MODEL,
                null=True,  # Allow null temporarily
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='subscriptions.subscription',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='subscriptions',
                to='subscriptions.subscriptionplan',
            ),
        ),
        # Populate 'user' field for existing subscriptions
        migrations.RunPython(populate_user_field),
        # Enforce NOT NULL constraint on the 'user' field
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscription',
                to=settings.AUTH_USER_MODEL,
                null=False,  # Remove null constraint
            ),
        ),
    ]
