# Generated by Django 5.1.4 on 2024-12-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
