# Generated by Django 5.1.4 on 2024-12-19 12:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_stripecustomer_default_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_payment_intent_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='customer',
        ),
        migrations.DeleteModel(
            name='StripeWebhookEvent',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_members_per_project',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_projects',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table=None,
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription'),
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
