# Generated by Django 5.1.4 on 2024-12-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
